#!/usr/bin/env python3

"""Enable or disable display standby when a USB device is added or removed."""

import logging
import subprocess

import pyudev

VENDOR_ID = 0x0BDA
PRODUCT_ID = 0x5411

PRODUCT_PREFIX = "{:x}/{:x}".format(VENDOR_ID, PRODUCT_ID)


def main():
    logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")
    context = pyudev.Context()
    monitor = pyudev.Monitor.from_netlink(context)
    monitor.filter_by(subsystem="usb")

    for device in iter(monitor.poll, None):
        device_type = device.get("DEVTYPE")
        product = device.get("PRODUCT")
        if device_type == "usb_device" and product.startswith(PRODUCT_PREFIX):
            if device.action == "add":
                logging.info("device added, enabling standby")
                set_standby("on")
            elif device.action == "remove":
                logging.info("device removed, disabling standby")
                set_standby("off")


def set_standby(status):
    try:
        subprocess.check_call(["xset", "dpms", "force", status])
    except subprocess.CalledProcessError as e:
        logging.warning("'xset' failed with status %s", e.returncode)


if __name__ == "__main__":
    main()
